# Generated by Django 4.2.8 on 2024-01-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_nuser_is_verified_nuser_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nuser',
            name='otp',
        ),
        migrations.AddField(
            model_name='nuser',
            name='otp_secret_key',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
