# Generated by Django 4.2.8 on 2024-01-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_nuser_otp_nuser_otp_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuser',
            name='otp_secret_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
